// SE UTILIZA PARA ITERAR SOBRE ELEMENTOS DE UN ARREGLO Y EJECUTAR UNA FUNCION PARA CADA ELEMENTO

// NO DEVUELVE UN NUEVO ARREGLO, TRABAJA SOBRE EL ORIGINAL 

const frutas = ['Manzana', 'Pera', 'Platano']

